---
title: "Boxplot with normalized values (vst)"
author: "Angeliki"
date: '2022-05-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries

```{r}
library("tidyverse")
```

# Loading Data

```{r}
n_data <- read_tsv(file = "../data/02_combined_vst.tsv.gz")
```
# Effect-of-treatment boxplots

CD3D, MS4A1, CTLA4, CD19 -> where shown to go back to normal
after treatment
IL10, CLEC12A, AURKA, MMP13, CLEC2B, CD58 -> are RA markers
and do not return to normal levels

### Wrangling 

```{r}
n_data_long <-
  n_data %>% 
  select(id,
         CD3D,
         MS4A1,
         CTLA4,
         CD19,
         IL10,
         CLEC12A,
         AURKA,
         MMP13,
         CLEC2B,
         CD58) %>%
  separate(col = id, 
           into = c("a", "b"),
           sep = "_",
           remove = FALSE) %>% 
  unite("condition", a:b, sep= " ") %>% 
  mutate( condition = case_when(
    condition == "RA pre" ~ "RA baseline",
    condition == "RA post" ~ "RA post-tDMARD",
    condition == "normal tissue" ~ "Normal",
    condition == "OA tissue" ~ "Osteoarthritis",
    condition == "AG tissue" ~ "Arthralgia",
    condition == "undiff tissue" ~ "Undifferentiated",
    condition == "RA tissue" ~ "RA early & late",
  )
  ) %>% 
  pivot_longer(cols = -c(id, condition),
               names_to = "gene" , 
               values_to = "expression_level")
n_data_long
```

# Visualization

With all the conditions (both long and treatment data)
```{r}
n_data_long %>% 
    ggplot(mapping = aes(
    x = condition,
    y = expression_level
  )
  ) +
  geom_boxplot(outlier.size = .5) +
  geom_jitter(aes(colour = condition),
              size = 0.7
    )+
  facet_wrap(vars(gene), scales = 'free_y') +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
   
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1)) 
```

Only treatment and normal data

```{r}
n_data_long %>% 
  filter(condition == "RA baseline" 
        | condition == "RA post-tDMARD"
        | condition == "Normal"
  ) %>% 
  ggplot(mapping = aes(
    x = condition,
    y = expression_level
  )
  ) +
  geom_boxplot(outlier.size = .5) +
  geom_jitter(aes(colour = condition),
              size = 0.7
    )+
  facet_wrap(vars(gene), scales = 'free_y') +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
   
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1))

```

