---
title: "Demographics"
output: html_document
date: '2022-04-28'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
data8 <- read_tsv("../data/02_large_w_meta_clean.tsv")
    
data8 %>% 
  ggplot(aes(age, fill=disease)) +
    geom_histogram(colour="#000000") -> histogram

data8 %>% 
  drop_na(age) %>% 
  filter(disease=="Normal") %>% 
  select(age) %>% 
  mean("age") 

means <- data8 %>% 
  drop_na(age) %>% 
  group_by(disease) %>% 
  summarize(Mean = round(mean(age, na.rm=TRUE))) %>% 
  as_tibble()

female <- data8 %>% 
  filter(sex=="F") %>% 
  group_by(disease) %>% 
  summarise(n())

male <- data8 %>% 
  filter(sex=="M") %>% 
  group_by(disease) %>% 
  summarise(n())

density <- data8 %>% 
  drop_na(age) %>% 
  ggplot(aes(age, fill=disease)) +
  geom_density(alpha=0.4) 

histogram <- data8 %>% 
  drop_na(sex) %>% 
  ggplot(aes(disease, fill=sex)) +
  theme(axis.text.x = element_text(angle = 90)) +
  geom_bar(alpha=0.4)

histogram +
  facet_wrap(vars(sex)) +
  scale_x_discrete(guide = guide_axis(angle = 90))+
  theme_minimal()

age_distribution_plot <- density + 
   geom_vline(data = means, aes(xintercept=Mean), size=0.5, color="red") +
   geom_label(data=means, size=2.5, 
             aes(x=Mean, y=0.015, label=paste0(Mean)),
             show.legend = FALSE) +
  ylab("Count")+
  xlab("Age of patients")+
  guides(fill=guide_legend(title="Condition"))+
  facet_wrap(vars(disease), ncol=1) +
  theme_minimal()

ggsave('../results/age_distr_plot.png', 
       age_distribution_plot, 
       width = 8, 
       height = 5, 
       bg = "transparent")
```

