---
title: "Javi plots"
output: html_document
date: '2022-04-21'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r}
library("tidyverse")
library("gtools")
#library("DESeq2")
```


# read datasets
```{r}
large_dataset <- read_tsv(file = "../data/05_large_w_meta_clean.tsv")
treatment_dataset <- read_tsv(file = "../data/06_treatment_w_meta_clean.tsv")
```

# this does not work
```{r}
pre_treatment <- treatment_dataset %>%
  select(-treatment, -sex, -age, -disease_duration, -acc_num) %>% 
  filter(grepl("pre", id)) %>% 
  mutate(id = str_sub(id, 8, -1))

post_treatment <- treatment_dataset %>% 
  select(-treatment, -sex, -age, -disease_duration, -acc_num) %>% 
  filter(grepl("post", id)) %>% 
  mutate(id = str_sub(id, 9, -1))

fold_change_treatment <- post_treatment %>% 
  select(-id)

```

# Random exploration



# PCA plots

# Heatplots

## Fold change pre post treatment (random choice to see if it works: all genes starting wit AA)
```{r}
logfold_treatment <- read_tsv(file = "../data/03_treatment_log2fc.tsv")

logfold_long <- logfold_treatment %>% 
  pivot_longer(cols = -c(id),
               names_to = "Genes" , 
               values_to = "log2fc")

logfold_long %>% filter(grepl("^AA", Genes)) %>% 
  ggplot(mapping = aes(x = Genes,
                       y = id,
                       fill = log2fc )) +
  geom_tile(alpha = 0.5) +
  scale_fill_gradient2(low = "blue",
                        mid = "white",
                        high = "red",
                        midpoint = 0) +
  theme_classic(base_size = 8) +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45,
                                   hjust = 1))
```
## Trying something different (genes important for T and/or B cell activation)

```{r}
lf_treatment_tc_genes <- logfold_treatment %>% 
  select("id", "ADAM8", "BCL11B", "CCL5", "CD3E", "CD5", "CD8A", "CD8B", "EOMES", 
         "GATA3", "ITGAL", "LCK", "NLRC3", "PRKCQ", "SIRPG", "SLAMF1", "SPN", 
         "TCF7", "THEMIS", "TRAC", "CD27", "LAX1", "SLA2", "ZAP70", "CD38", 
         "CD79B", "IGHD", "IKZF3", "MZB1", "TBC1D10C") %>%
  pivot_longer(cols = -c(id),
               names_to = "Genes" , 
               values_to = "log2fc") 
    
    
# factor(Genes,levels =  c("ADAM8", "BCL11B", "CCL5", "CD3E", "CD5", "CD8A", "CD8B", "EOMES", "GATA3", "ITGAL", "LCK", "NLRC3", "PRKCQ", "SIRPG", "SLAMF1", "SPN", "TCF7", "THEMIS", "TRAC", "CD27", "LAX1", "SLA2", "ZAP70", "CD38", "CD79B", "IGHD", "IKZF3", "MZB1", "TBC1D10C")) 

lf_treatment_tc_genes %>%
  ggplot(mapping = aes(x = id,
                       y = Genes,
                       fill = log2fc )) +
  geom_tile(alpha = 0.5) +
  scale_fill_gradient2(low = "blue",
                        mid = "white",
                        high = "red",
                        midpoint = 0) +
  theme_classic(base_size = 8) +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45,
                                   hjust = 1))
  
```

## filtering significantly up/down expressed genes (log2fc > 2) 
I think we calculated the fold change backwards
```{r}
transpose_logfold_treatment <- logfold_long %>% 
  pivot_wider(names_from = id, values_from = log2fc)

selected_genes_treatment <- transpose_logfold_treatment %>%  
  mutate(mean_log2fc = rowMeans(across(where(is.numeric)))) %>% 
  filter(mean_log2fc >= 2 | mean_log2fc <= -2)

selected_genes_treatment_long <- selected_genes_treatment %>% 
  select(-mean_log2fc) %>% 
  pivot_longer(cols = -c(Genes),
               names_to = "id" , 
               values_to = "log2fc")


selected_genes_treatment_long %>%
  ggplot(mapping = aes(x = Genes,
                       y = id,
                       fill = log2fc )) +
  geom_tile(alpha = 0.5) +
  scale_fill_gradient2(low = "blue",
                        mid = "white",
                        high = "red",
                        midpoint = 0) +
  theme_classic(base_size = 8) +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 45,
                                   hjust = 1))

```



