title: "Plots"
output: html_document
date: '2022-04-20'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(compositions)
library(cowplot)
library(ggplot2)
library(scales)
library(tidyr)
library(broom)
```


```{r}
combined <- read_tsv(file = "../data/02_combined_vst.tsv.gz")
combined_meta <- read_tsv(file = "../data/02_combined_meta.tsv")
combined_w_meta <- combined %>% 
  left_join(combined_meta)
```

PCA - differentiated by sex
```{r}
male_combined_w_meta <- combined_w_meta %>% 
  filter(sex == 'M' & (disease == 'Normal' | disease == 'Rheumatoid arthritis (early)' | disease == 'Rheumatoid arthritis (established)'))
female_combined_w_meta <- combined_w_meta %>% 
  filter(sex == 'F' & (disease == 'Normal' | disease == 'Rheumatoid arthritis (early)' | disease == 'Rheumatoid arthritis (established)'))

male_combined_w_meta_numeric <- male_combined_w_meta %>%
  select(!(age)) %>% 
  select(where(is.numeric)) 

male_pca_fit <- male_combined_w_meta_numeric[, which(colSums(abs(male_combined_w_meta_numeric)) != 0)]  %>%
  prcomp() # do PCA on scaled data

female_combined_w_meta_numeric <- female_combined_w_meta %>%
  select(!(age)) %>% 
  select(where(is.numeric))    # retain only numeric columns
  
female_pca_fit <- female_combined_w_meta_numeric[, which(colSums(abs(female_combined_w_meta_numeric)) != 0)] %>%
  prcomp() # do PCA on scaled data

male_pca_plot <- male_pca_fit %>%
  augment(male_combined_w_meta) %>% # add original dataset back in
  ggplot(aes(.fittedPC1, 
             .fittedPC2, 
             color = disease)) + 
  geom_point(size = 1.5) +
  labs(x = 'PC1',
       y = 'PC2',
       title = 'PCA plot of diseases in males') +
  theme_minimal()

female_pca_plot <- female_pca_fit %>%
  augment(female_combined_w_meta) %>% # add original dataset back in
  ggplot(aes(.fittedPC1, 
             .fittedPC2, 
             color = disease)) + 
  geom_point(size = 1.5) +
  labs(x = 'PC1',
       y = 'PC2',
       title = 'PCA plot of diseases in females') +
  theme_minimal()

legend <- get_legend(male_pca_plot + theme(legend.position = 'bottom'))

prow <- plot_grid(male_pca_plot + theme(legend.position = 'null'), 
                      female_pca_plot + theme(legend.position = 'null'), rel_widths = c(2, 2))
two_pcas <- plot_grid(prow, legend, ncol = 1, rel_heights = c(1, .1))
two_pcas 
ggsave('pca_vst.png', two_pcas, width = 10, height = 5)
```


```{r}
male_pca_fit %>%
  tidy(matrix = "eigenvalues")

female_pca_fit %>%
  tidy(matrix = "eigenvalues")


arrow_style <- arrow(
  angle = 20, ends = "first", type = "closed", length = grid::unit(8, "pt")
)

# plot rotation matrix
male_pca_fit %>%
  tidy(matrix = "rotation") %>%
  pivot_wider(names_from = "PC", 
              names_prefix = "PC", 
              values_from = "value") %>%
  ggplot(aes(PC1, PC2, PC3)) +
  geom_segment(xend = 0, 
               yend = 0,
               arrow = arrow_style) +
  geom_text(
    aes(label = column),
    hjust = 1, 
    nudge_x = -0.02, 
    color = "#904C2F"
  ) +
  xlim(-1.25, .5) + ylim(-.5, 1) +
  coord_fixed()  # fix aspect ratio to 1:1

female_pca_fit %>%
  tidy(matrix = "rotation") %>%
  pivot_wider(names_from = "PC", 
              names_prefix = "PC", 
              values_from = "value") %>%
  ggplot(aes(PC1, PC2)) +
  geom_segment(xend = 0, 
               yend = 0, 
               arrow = arrow_style) +
  geom_text(
    aes(label = column),
    hjust = 1, 
    nudge_x = -0.02, 
    color = "#904C2F"
  ) +
  xlim(-1.25, .5) + ylim(-.5, 1) +
  coord_fixed()  # fix aspect ratio to 1:1

```




```{r}
male_comp_perc <- male_pca_fit %>%
  tidy(matrix = "eigenvalues") %>%
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9", 
           alpha = 0.8) +
  scale_x_continuous(breaks = 1:10) +
  scale_y_continuous(
    labels = scales::percent_format(),
    expand = expansion(mult = c(0, 0.01))
  ) 

female_comp_perc <- female_pca_fit %>%
  tidy(matrix = "eigenvalues") %>%
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9", 
           alpha = 0.8) +
  scale_x_continuous(breaks = 1:10) +
  scale_y_continuous(
    labels = scales::percent_format(),
    expand = expansion(mult = c(0, 0.01))
  ) 

prow_comps <- plot_grid(male_comp_perc, 
                      female_comp_perc, nrow = 2)
two_pca_comps <- plot_grid(prow_comps)
two_pca_comps
```


KMEANS - females
```{r}
tidy_female_pca <- female_pca_fit %>% 
  tidy() 

female_points <- tidy_female_pca %>% 
  filter(PC==1 | PC==2) %>% 
  pivot_wider(names_from = 'PC', values_from = 'value') %>% 
  select(-row)


colnames(female_points)[1] = 'PC1'
colnames(female_points)[2] = 'PC2'

kclusts <- 
  tibble(k = 2:3) %>%
  mutate(
    kclust = map(k, ~kmeans(female_points, .x)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, female_points)
  )

clusters <- 
  kclusts %>%
  unnest(cols = c(tidied))

assignments <- 
  kclusts %>% 
  unnest(cols = c(augmented))

clusterings <- 
  kclusts %>%
  unnest(cols = c(glanced))

p1 <- assignments %>% 
  ggplot(aes(x = PC1, 
             y = PC2)) +
  geom_point(aes(color = .cluster), alpha = 0.8) +
  labs(title = 'Plot of clustered PCA components',
       color = 'cluster') +
  facet_wrap(~k)
```



KMEANS - males
```{r}
tidy_male_pca <- male_pca_fit %>% 
  tidy() 

male_points <- tidy_male_pca %>% 
  filter(PC==1 | PC==2) %>% 
  pivot_wider(names_from = 'PC', values_from = 'value') %>% 
  select(-row)


colnames(male_points)[1] = 'PC1'
colnames(male_points)[2] = 'PC2'

kclusts <- 
  tibble(k = 2:3) %>%
  mutate(
    kclust = map(k, ~kmeans(male_points, .x)),
    tidied = map(kclust, tidy),
    glanced = map(kclust, glance),
    augmented = map(kclust, augment, male_points)
  )

clusters <- 
  kclusts %>%
  unnest(cols = c(tidied))

assignments <- 
  kclusts %>% 
  unnest(cols = c(augmented))

clusterings <- 
  kclusts %>%
  unnest(cols = c(glanced))

p2 <- assignments %>% 
  ggplot(aes(x = PC1, 
             y = PC2)) +
  geom_point(aes(color = .cluster), alpha = 0.8) +
  labs(title = 'Plot of clustered PCA components',
       color = 'cluster') +
  facet_wrap(~k)
```


```{r}
prow_clus <- plot_grid(female_pca_plot + theme(legend.position = 'bottom') + guides(colour = guide_legend(nrow = 3)), p1 + theme(legend.position = 'bottom') + guides(colour = guide_legend(nrow = 3)), rel_widths = c(2, 4))
```

```{r}
prow_clus_m <- plot_grid(male_pca_plot + theme(legend.position = 'bottom') + guides(colour = guide_legend(nrow = 3)), p2 + theme(legend.position = 'bottom') + guides(colour = guide_legend(nrow = 3)), rel_widths = c(2, 4))
prow_clus_m
```

