# Run all scripts ---------------------------------------------------------
source(file = "R/01_load.R")
source(file = "R/02_clean.R")
source(file = "R/03_augment.R")
source(file = "R/04_analysis_i.R")
source(file = "R/05-analysis_ii_pca.R")
source(file = "R/06-analysis_iii_boxpl_nrml.R")
source(file = "R/07-analysis_iv_eda.R")
source(file = "R/08-analysis_V_diff_expr.R")
source(file = "R/09-analysis_javi.R")
source(file = "R/10-analysis_model.R")
source(file = "R/11-analysis_log_reg.R")